name: Deploy backend to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: forecasting-ai-powered-ddarbmdqe3dzdccg   # <-- your Web App name
      PACKAGE_PATH: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Sanity check backend contents
        run: |
          ls -la $PACKAGE_PATH
          test -f $PACKAGE_PATH/app.py || (echo "backend/app.py not found"; exit 1)
          test -f $PACKAGE_PATH/requirements.txt || (echo "backend/requirements.txt not found"; exit 1)

      # You can deploy a directory directly; the action will zip it.
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # from the Web App (not SWA)
          package: ${{ env.PACKAGE_PATH }}
