name: Build and deploy Python app to Azure Web App - forecasting-ai-powered

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'    # Use a version Azure supports; 3.13 is not broadly supported yet

      - name: Create and start virtual environment
        working-directory: backend
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend/            # upload only backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8753B93AE9B746BF977FF3CB512EC6DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC308B8466AB4F5688A1C6B77816B49C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22FBFD431DDF44469B935A77E7DDBFEA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'forecasting-ai-powered'
          slot-name: 'Production'
          package: '.'              # artifact root now *is* backend
