name: Deploy backend to Azure Web App (Flask)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-webapp.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write          # <-- REQUIRED for OIDC
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09AD0EC5BCD245FB920C5C56429603A9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A002F8F02C8041DD95ACFD4F69D8F564 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E0A17BD9D2F4F5B8F7E9F705CE2503A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'forecasting-ai-powered'
          slot-name: 'Production'
          package: backend
