name: Deploy frontend to Azure Static Web Apps

on:
  push:
    branches: [ main ]
    # re-deploy when frontend or this workflow changes
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy_frontend.yml'
  workflow_dispatch:

concurrency:
  group: swa-frontend
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you want to pin Node for the build, uncomment:
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # 🔒 REQUIRED: set this secret in your repo as the SWA deployment token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          # (Optional) lets the action comment on PRs, etc.
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          # Where your frontend lives in the repo (change if different)
          app_location: frontend

          # Where the built files end up (Vite defaults to "dist")
          output_location: dist

          # Have the action build the app for you
          app_build_command: npm ci && npm run build

          # You are NOT using SWA-managed Functions for the API
          api_location: ''

        # Build-time env for Vite (picked up by import.meta.env.VITE_API_BASE)
        env:
          # Prefer a repo-level Variable named VITE_API_BASE; otherwise use this inline default.
          VITE_API_BASE: ${{ vars.VITE_API_BASE || 'https://forecasting-ai-powered-ddarbmdqe3dzdccg.canadacentral-01.azurewebsites.net/api' }}
