name: Deploy backend to Azure Web App (Flask)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-webapp.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use a version Azure supports (e.g., 3.10 or 3.11). 3.13 is often not yet supported.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create a zip of just the backend folder for deployment
      - name: Archive backend
        working-directory: backend
        run: |
          zip -r ../backend.zip . -x "venv/**" "__pycache__/**" "*.pyc"

      - uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8753B93AE9B746BF977FF3CB512EC6DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC308B8466AB4F5688A1C6B77816B49C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22FBFD431DDF44469B935A77E7DDBFEA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: forecasting-ai-powered
          slot-name: Production
          package: backend.zip
